/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora.guicalculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author josem
 */
public class GuiCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form GuiCalculadora
     */
    public GuiCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblValor1 = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        txtValor2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        lblResultado = new javax.swing.JLabel();
        lblGrados = new javax.swing.JLabel();
        txtGrados = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnSumar = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnCelsiusAFahrenheit = new javax.swing.JButton();
        btnFahrenheitACelsius = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plTitulo.setBackground(new java.awt.Color(204, 204, 204));
        plTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Calculadora");
        plTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 39, -1, -1));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/guicalculadora/icons8-calculadora-40.png"))); // NOI18N
        lblIcono.setText("jLabel");
        plTitulo.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 29, 49, 48));

        getContentPane().add(plTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 586, 90));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValor1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblValor1.setForeground(new java.awt.Color(0, 0, 0));
        lblValor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValor1.setText("Valor 1 :");
        jPanel1.add(lblValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 24, -1, -1));

        lblValor2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblValor2.setForeground(new java.awt.Color(0, 0, 0));
        lblValor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValor2.setText("Valor 2 :");
        jPanel1.add(lblValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 69, -1, -1));

        txtValor1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor1ActionPerformed(evt);
            }
        });
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor1KeyTyped(evt);
            }
        });
        jPanel1.add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 24, 74, -1));

        txtValor2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor2ActionPerformed(evt);
            }
        });
        txtValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor2KeyTyped(evt);
            }
        });
        jPanel1.add(txtValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 69, 74, -1));

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 227, -1, -1));

        lblResultado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(0, 0, 0));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("Resultado");
        jPanel1.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 185, -1, -1));

        lblGrados.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblGrados.setForeground(new java.awt.Color(0, 0, 0));
        lblGrados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrados.setText("Grados :");
        jPanel1.add(lblGrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 126, -1, -1));

        txtGrados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradosActionPerformed(evt);
            }
        });
        txtGrados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGradosKeyTyped(evt);
            }
        });
        jPanel1.add(txtGrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 126, 74, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 400, 340));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnSumar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSumar.setText("Sumar");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        btnRestar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRestar.setText("Restar");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });

        btnMultiplicar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        btnDividir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDividir.setText("Dividir");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btnCelsiusAFahrenheit.setText("De Celsius a Fahrenheit");
        btnCelsiusAFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelsiusAFahrenheitActionPerformed(evt);
            }
        });

        btnFahrenheitACelsius.setText("De Fahrenheit a Celsius");
        btnFahrenheitACelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFahrenheitACelsiusActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFahrenheitACelsius)
                            .addComponent(btnCelsiusAFahrenheit)
                            .addComponent(btnDividir)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRestar)
                            .addComponent(btnMultiplicar)
                            .addComponent(btnSumar))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnSumar)
                .addGap(18, 18, 18)
                .addComponent(btnRestar)
                .addGap(18, 18, 18)
                .addComponent(btnMultiplicar)
                .addGap(18, 18, 18)
                .addComponent(btnDividir)
                .addGap(18, 18, 18)
                .addComponent(btnCelsiusAFahrenheit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFahrenheitACelsius)
                .addGap(24, 24, 24)
                .addComponent(btnLimpiar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 190, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1ActionPerformed
       
    }//GEN-LAST:event_txtValor1ActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        sumarValores();
        validarValor();
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnFahrenheitACelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFahrenheitACelsiusActionPerformed
        calcularFaC();
        
    }//GEN-LAST:event_btnFahrenheitACelsiusActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        restarValores();
        
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        multiplicarValores();
        
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        dividirValores();
        
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnCelsiusAFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelsiusAFahrenheitActionPerformed
        calcularCaF();
        
    }//GEN-LAST:event_btnCelsiusAFahrenheitActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtValor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {

            JOptionPane.showMessageDialog(null, "Ingresar un valor para realizar la operacion");
            evt.consume();
        }

    }//GEN-LAST:event_txtValor1KeyTyped

    private void txtValor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor2KeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {

            JOptionPane.showMessageDialog(null, "Ingresar un valor para realizar la operacion");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor2KeyTyped

    private void txtGradosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGradosKeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {

            JOptionPane.showMessageDialog(null, "Ingresar un valor para realizar la operacion");
            evt.consume();
        }
    }//GEN-LAST:event_txtGradosKeyTyped

    private void txtValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor2ActionPerformed
        
    }//GEN-LAST:event_txtValor2ActionPerformed

    private void txtGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradosActionPerformed
        
    }//GEN-LAST:event_txtGradosActionPerformed

    private void sumarValores() {
        CalculadoraMetodos cal = new CalculadoraMetodos();
        Double respuesta = cal.sumar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));

        txtResultado.setText(respuesta + "");
    }

    private void restarValores() {
        CalculadoraMetodos cal = new CalculadoraMetodos();
        Double respuesta = cal.restar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));

        txtResultado.setText(respuesta + "");
    }

    private void multiplicarValores() {
        CalculadoraMetodos cal = new CalculadoraMetodos();
        Double respuesta = cal.multiplicar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));

        txtResultado.setText(respuesta + "");

    }

    private void dividirValores() {
        CalculadoraMetodos cal = new CalculadoraMetodos();
        Double respuesta = cal.dividir(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));

        txtResultado.setText(respuesta + "");

    }

    private void calcularCaF() {
        ConvertidorGrados con = new ConvertidorGrados();
        Double respuesta = con.fahrenheit(Double.parseDouble(txtGrados.getText()));

        txtResultado.setText(respuesta + "");

    }

    private void calcularFaC() {
        ConvertidorGrados con = new ConvertidorGrados();
        Double respuesta = con.celsius(Double.parseDouble(txtGrados.getText()));

        txtResultado.setText(respuesta + "");

    }

    private void limpiarCampos() {
        txtValor1.setText("");
        txtValor2.setText("");
        txtGrados.setText("");
        txtResultado.setText("");
        txtValor1.requestFocus();
    }

    private void validarValor() {
        if (txtValor1.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Favor ingresar datos a valor 1, ya que está vacío.");
            txtValor1.requestFocus();
        } else if (txtValor2.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Favor ingresar datos a valor 2, ya que está vacío.");
            txtValor2.requestFocus();
        }/*else if (txtGrados.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Favor ingresar datos a Grados, ya que está vacío.");
            txtGrados.requestFocus();
        }*/

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCelsiusAFahrenheit;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnFahrenheitACelsius;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrados;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JPanel plTitulo;
    private javax.swing.JTextField txtGrados;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables

}
